edition = "2021"
max_width = 100
use_small_heuristics = "Max"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
newline_style = "Unix"
wrap_comments = true
binop_separator = "Back"
comment_width = 120
format_code_in_doc_comments = true
overflow_delimited_expr = true
reorder_imports = true
trailing_comma = "Vertical"
trailing_semicolon = false
use_field_init_shorthand = true
