version: 2

run:
  timeout: 5m
  tests: true
  allow-parallel-runners: true

linters-settings:
  govet:
    check-shadowing: true
  staticcheck:
    checks:
      - all

linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - errcheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
